version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\bvestl-fs
skip_tags: true

environment:
  VCPKG_ROOT: C:\Tools\vcpkg

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: cd C:\Tools\vcpkg
  - cmd: git pull --ff -q
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: C:\Python37-x64\python.exe ./tools/vcpkg/setup.py --vcpkg-dir=c:/tools/vcpkg

before_build:
  - cmd: cd C:\projects\bvestl-fs
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64" -Thost=x64 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: C:\projects\bvestl-fs\build\bvestl-fs.sln
  verbosity: minimal

cache: 
  - c:\tools\vcpkg\downloads\ -> tools/ci/appveyor.yaml, tools/vcpkg/setup.py
  - c:\tools\vcpkg\installed\ -> tools/ci/appveyor.yaml, tools/vcpkg/setup.py
  - c:\tools\vcpkg\packages\ -> tools/ci/appveyor.yaml, tools/vcpkg/setup.py

test_script:
  - cmd: C:\projects\bvestl-fs\build\%CONFIGURATION%\path_demo.exe -- C:\projects\bvestl-fs\build\%CONFIGURATION%\test-tree

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
