stages:
  - build
  - test
  # - post build
  # - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - build-vcpkg

after_script:
  - cmake -E remove_directory build-vcpkg/buildtrees

build:clang-8:debug:
  stage: build
  tags:
    - linux
  script:
    - nice python3.7 build.py
    - mkdir build-clang8-debug
    - nice cmake -S . -B build-clang8-debug 
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/clang-8 
      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/clang++-8
      -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake 
      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=lld"
      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      -GNinja
    - nice ninja -C build-clang8-debug
  artifacts:
    paths:
      - build-clang8-debug

build:clang-8:asan-ubsan:
  stage: build
  tags:
    - linux
  script:
    - nice python3.7 build.py
    - mkdir build-clang8-asan-ubsan
    - nice cmake -S . -B build-clang8-asan-ubsan 
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/clang-8 
      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/clang++-8
      -DSANITIZE_{ADDRESS,UNDEFINED}=On
      -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake 
      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=lld"
      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      -GNinja
    - nice ninja -C build-clang8-asan-ubsan
  artifacts:
    paths:
      - build-clang8-asan-ubsan

build:clang-8:tsan:
  stage: build
  tags:
    - linux
  script:
    - nice python3.7 build.py
    - mkdir build-clang8-tsan
    - nice cmake -S . -B build-clang8-tsan 
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/clang-8 
      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/clang++-8
      -DSANITIZE_THREAD=On
      -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake 
      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=lld"
      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      -GNinja
    - nice ninja -C build-clang8-tsan
  artifacts:
    paths:
      - build-clang8-tsan

build:clang-8:release:
  stage: build
  tags:
    - linux
  script:
    - nice python3.7 build.py
    - mkdir build-clang8-release
    - nice cmake -S . -B build-clang8-release 
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/clang-8 
      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/clang++-8
      -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake 
      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=lld"
      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      -GNinja
    - nice ninja -C build-clang8-release
  artifacts:
    paths:
      - build-clang8-release

build:gcc-7:debug:
  stage: build
  tags:
    - linux
  script:
    - nice python3.7 build.py
    - mkdir build-gcc7-debug
    - nice cmake -S . -B build-gcc7-debug 
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/gcc-7
      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/g++-7
      -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake 
      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=gold"
      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      -GNinja
    - nice ninja -C build-gcc7-debug
  artifacts:
    paths:
      - build-gcc7-debug

build:gcc-7:release:
  stage: build
  tags:
    - linux
  script:
    - nice python3.7 build.py
    - mkdir build-gcc7-release
    - nice cmake -S . -B build-gcc7-release 
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/gcc-7
      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/g++-7
      -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake 
      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=gold"
      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      -GNinja
    - nice ninja -C build-gcc7-release
  artifacts:
    paths:
      - build-gcc7-release

test:clang-8:debug:
  stage: test
  tags:
    - linux
  cache:
    policy: pull
    paths:
      - build-vcpkg
  script:
    - LD_LIBRARY_PATH=$PWD/build-clang8-debug nice ./build-clang8-debug/path_demo -- ./build-clang8-debug/test-tree
  dependencies:
    - build:clang-8:debug

test:clang-8:asan-ubsan:
  stage: test
  tags:
    - linux
  cache:
    policy: pull
    paths:
      - build-vcpkg
  script:
    - LD_LIBRARY_PATH=$PWD/build-clang8-asan-ubsan nice ./build-clang8-asan-ubsan/path_demo -- ./build-clang8-asan-ubsan/test-tree
  dependencies:
    - build:clang-8:asan-ubsan

test:clang-8:tsan:
  stage: test
  tags:
    - linux
  cache:
    policy: pull
    paths:
      - build-vcpkg
  script:
    - LD_LIBRARY_PATH=$PWD/build-clang8-tsan nice ./build-clang8-tsan/path_demo -- ./build-clang8-tsan/test-tree
  dependencies:
    - build:clang-8:tsan

test:clang-8:release:
  stage: test
  tags:
    - linux
  cache:
    policy: pull
    paths:
      - build-vcpkg
  script:
    - LD_LIBRARY_PATH=$PWD/build-clang8-release nice ./build-clang8-release/path_demo -- ./build-clang8-release/test-tree
  dependencies:
    - build:clang-8:release

test:gcc-7:debug:
  stage: test
  tags:
    - linux
  cache:
    policy: pull
    paths:
      - build-vcpkg
  script:
    - LD_LIBRARY_PATH=$PWD/build-gcc7-debug nice ./build-gcc7-debug/path_demo -- ./build-gcc7-debug/test-tree
  dependencies:
    - build:gcc-7:debug

test:gcc-7:release:
  stage: test
  tags:
    - linux
  cache:
    policy: pull
    paths:
      - build-vcpkg
  script:
    - LD_LIBRARY_PATH=$PWD/build-gcc7-release nice ./build-gcc7-release/path_demo -- ./build-gcc7-release/test-tree
  dependencies:
    - build:gcc-7:release
